## Notes
**df_pq** = dataset voor contentbasedfiltering. \
**df_small** = contentbased maar kleinere dataset dan df_pq. \
**playlist_counts** = dataset over hoe vaak een arties voorkomt in 2000 playlists. \
**df_listeners** = monthly listener dataset van kaggle met iets van 3000 entries. \
**df_kwob** = dataset met monthly listeners van site kworb, dit zijn iets van 25.000. entries. \
**df_artists** = dataset met artiesten die zowel in playlist_counts als in df_kwob zitten.

In [1]:
import pandas as pd
import os
import json

In [2]:
# Dit is die iets kleinere dataset, gaan we denk ik niet gebruiken
# https://www.kaggle.com/code/vatsalmavani/music-recommendation-system-using-spotify-dataset/notebook
path = os.path.join('.', 'data', 'data.csv')
print(f"Je zoekt nu hier: {os.path.abspath(path)}")

df_small = pd.read_csv(path, sep=",", on_bad_lines='skip')
df_small.head()

Je zoekt nu hier: C:\Users\saark\OneDrive\Documenten\GitHub\recsys\data\data.csv

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [3]:
# Dit is de spotify 1 million tracks dataset
# https://www.kaggle.com/datasets/amitanshjoshi/spotify-1million-tracks/data
df_pq = pd.read_parquet('./data/spotify_data.parquet')
df_pq.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1159764 entries, 0 to 1159763
Data columns (total 20 columns):
 #   Column            Non-Null Count    Dtype
---  ------            --------------    -----
 0   Unnamed: 0        1159764 non-null  int64
 1   artist_name       1159749 non-null  object
 2   track_name        1159763 non-null  object
 3   track_id          1159764 non-null  object
 4   popularity        1159764 non-null  int64
 5   year              1159764 non-null  int64
 6   genre             1159764 non-null  object
 7   danceability      1159764 non-null  float64
 8   energy            1159764 non-null  float64
 9   key               1159764 non-null  int64
 10  loudness          1159764 non-null  float64
 11  mode              1159764 non-null  int64
 12  speechiness       1159764 non-null  float64
 13  acousticness      1159764 non-null  float64
 14  instrumentalness  1159764 non-null  float64
 15  liveness          1159764 non-null  float64
 16  valence           1159764 non-null  float64
 17  tempo             1159764 non-null  float64
 18  duration_ms       1159764 non-null  int64
 19  time_signature    1159764 non-null  int64
dtypes: float64(9), int64(7), object(4)
memory usage: 177.0+ MB

In [4]:
# Dit is de een deel van de dataset van spotify van 1000 random playlists
# https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files
with open('data/mpd.slice.0-999.json') as f:
    data = json.load(f)

df_spot = pd.DataFrame(data['playlists'])
df_spot.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN

In [5]:
# Dit is het tweede deel van de dataset van spotify van 1000 random playlists
# https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files
with open('data/mpd.slice.1000-1999.json') as f:
    data = json.load(f)

df_spot2 = pd.DataFrame(data['playlists'])
df_spot2.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN

In [6]:
# Hier wordt er per artiest geteld hoe vaak hun naam voorkomt in de kolom tracks.
# Hierdoor hou je bij hoe vaak een bepaalde
# artiest voorkomt in 1000 playlists.
df_tracks1 = df_spot.explode('tracks')
df_tracks1['artist_name'] = df_tracks1['tracks'].apply(lambda x: x['artist_name'])

artist_counts1 = df_tracks1['artist_name'].value_counts()
artist_counts1.head()

artist_name
Drake             939
Kanye West        415
Kendrick Lamar    385
Rihanna           350
Eminem            332
Name: count, dtype: int64

In [7]:
# Hier wordt er per artiest geteld hoe vaak hun naam voorkomt in de kolom tracks.
# Hierdoor hou je bij hoe vaak een bepaalde
# artiest voorkomt in 1000 playlists. Maar dan hier bij het tweede deel.
df_tracks2 = df_spot2.explode('tracks')
df_tracks2['artist_name'] = df_tracks2['tracks'].apply(lambda x: x['artist_name'])

artist_counts2 = df_tracks2['artist_name'].value_counts()
artist_counts2.head()

artist_name
Drake             990
The Beatles       351
The Weeknd        348
Kendrick Lamar    337
Kanye West        314
Name: count, dtype: int64

In [8]:
# Hier worden de twee dataframes van de 1000 playlists gecombineerd
# om totaal te berekenen hoe vaak een artiest voorkomt in 2000
# playlists.
combined = pd.concat([df_spot, df_spot2], ignore_index=True)
combined.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN

In [9]:
# Dit zijn alle counts uit 2 files bij elkaar opgeteld. Dus hoe vaak een bepaalde artiest in 2000 playlists voorkomt.
df_tracks = combined.explode('tracks')
df_tracks['artist_name'] = df_tracks['tracks'].apply(lambda x: x['artist_name'])

artist_counts = df_tracks['artist_name'].value_counts()
playlist_counts = artist_counts.reset_index()
playlist_counts.columns = ["artist_name", "playlist_count"]
playlist_counts.head()

      artist_name  playlist_count
0           Drake            1929
1      Kanye West             729
2  Kendrick Lamar             722
3      The Weeknd             644
4         Rihanna             613

In [10]:
# Dit is de montly listeners dataset
# https://www.kaggle.com/datasets/meeratif/spotify-top-artists-by-monthly-listeners/data
df_listeners = pd.read_csv('./data/listeners.csv')
df_listeners = df_listeners.rename(columns={"Artist": "artist_name","Listeners": "monthly_listeners"})
df_listeners = df_listeners[["artist_name", "monthly_listeners"]]
#df_listeners[df_listeners["artist_name"] == "Jason Mraz"]
df_listeners.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   artist_name        2500 non-null   object
 1   monthly_listeners  2500 non-null   object
dtypes: object(2)
memory usage: 39.2+ KB

In [11]:
# Dit is data die ik geexctract heb  van https://kworb.net/spotify/listeners.html
# Deze heb ik in een csv bestand gezet en hier ingeladen.
df_kwob = pd.read_csv('./data/kwob_data.csv')
df_kwob = df_kwob.rename(columns={"Artist": "artist_name","Listeners": "monthly_listeners"})
df_kwob.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 24294 entries, 0 to 24293
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   #                  24294 non-null  int64
 1   artist_name        24293 non-null  object
 2   monthly_listeners  24294 non-null  int64
 3   Daily +/-          24294 non-null  int64
 4   Peak               2500 non-null   float64
 5   PkListeners        24294 non-null  int64
 6   page               24294 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 1.3+ MB

In [12]:
# Hier merge ik de datasets zodat we één dataframe hebben met alle nodige kolommen
df_merged = df_pq.merge(playlist_counts, on="artist_name", how="left")
df_merged = df_merged.merge(df_kwob, on="artist_name", how="left")

df_artists = df_merged.groupby("artist_name")[["playlist_count","monthly_listeners"]].first().reset_index()
df_artists = df_artists.dropna(subset=["playlist_count", "monthly_listeners"])

df_artists.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4078 entries, 4 to 63892
Data columns (total 3 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   artist_name        4078 non-null   object
 1   playlist_count     4078 non-null   float64
 2   monthly_listeners  4078 non-null   float64
dtypes: float64(2), object(1)
memory usage: 127.4+ KB

In [13]:
len(df_pq["artist_name"].unique())

64159

In [14]:
len(playlist_counts["artist_name"].unique())

14914

In [15]:
len(df_kwob["artist_name"].unique())

24214

In [16]:
len(df_artists["artist_name"].unique())

4078

In [17]:
unmatched_kwob = set(df_kwob["artist_name"]) - set(playlist_counts["artist_name"])
len(unmatched_kwob)

19167

In [18]:
unmatched_playlist = set(playlist_counts["artist_name"]) - set(df_kwob["artist_name"])
len(unmatched_playlist)

9867