In [1]:
import pandas as pd
import os
import json

# Dit is die iets kleinere dataset, gaan we denk ik niet gebruiken
# https://www.kaggle.com/code/vatsalmavani/music-recommendation-system-using-spotify-dataset/notebook
path = os.path.join('.', 'data', 'data.csv')
print(f"Je zoekt nu hier: {os.path.abspath(path)}")

df_small = pd.read_csv(path, sep=",", on_bad_lines='skip')
df_small.head()

Je zoekt nu hier: C:\Users\saark\OneDrive\Documenten\GitHub\recsys\data\data.csv

,valence,year,acousticness,artists,danceability,duration_ms,energy,explicit,id,instrumentalness,key,liveness,loudness,mode,name,popularity,release_date,speechiness,tempo
0,0.0594,1921,0.982,"['Sergei Rachmaninoff', 'James Levine', 'Berli...",0.279,831667,0.211,0,4BJqT0PrAfrxzMOxytFOIz,0.878000,10,0.665,-20.096,1,"Piano Concerto No. 3 in D Minor, Op. 30: III. ...",4,1921,0.0366,80.954
1,0.9630,1921,0.732,['Dennis Day'],0.819,180533,0.341,0,7xPhfUan2yNtyFG0cUWkt8,0.000000,7,0.160,-12.441,1,Clancy Lowered the Boom,5,1921,0.4150,60.936
2,0.0394,1921,0.961,['KHP Kridhamardawa Karaton Ngayogyakarta Hadi...,0.328,500062,0.166,0,1o6I8BglA6ylDMrIELygv1,0.913000,3,0.101,-14.850,1,Gati Bali,5,1921,0.0339,110.339
3,0.1650,1921,0.967,['Frank Parker'],0.275,210000,0.309,0,3ftBPsC5vPBKxYSee08FDH,0.000028,5,0.381,-9.316,1,Danny Boy,3,1921,0.0354,100.109
4,0.2530,1921,0.957,['Phil Regan'],0.418,166693,0.193,0,4d6HGyGT8e121BsdKmw9v6,0.000002,3,0.229,-10.096,1,When Irish Eyes Are Smiling,2,1921,0.0380,101.665

In [2]:
# Dit is de spotify 1 million tracks dataset
# https://www.kaggle.com/datasets/amitanshjoshi/spotify-1million-tracks/data
df_pq = pd.read_parquet('./data/spotify_data.parquet')
df_pq.head()

,Unnamed: 0,artist_name,track_name,track_id,popularity,year,genre,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,duration_ms,time_signature
0,0,Jason Mraz,I Won't Give Up,53QF56cjZA9RTuuMZDrSA6,68,2012,acoustic,0.483,0.303,4,-10.058,1,0.0429,0.6940,0.000000,0.1150,0.139,133.406,240166,3
1,1,Jason Mraz,93 Million Miles,1s8tP3jP4GZcyHDsjvw218,50,2012,acoustic,0.572,0.454,3,-10.286,1,0.0258,0.4770,0.000014,0.0974,0.515,140.182,216387,4
2,2,Joshua Hyslop,Do Not Let Me Go,7BRCa8MPiyuvr2VU3O9W0F,57,2012,acoustic,0.409,0.234,3,-13.711,1,0.0323,0.3380,0.000050,0.0895,0.145,139.832,158960,4
3,3,Boyce Avenue,Fast Car,63wsZUhUZLlh1OsyrZq7sz,58,2012,acoustic,0.392,0.251,10,-9.845,1,0.0363,0.8070,0.000000,0.0797,0.508,204.961,304293,4
4,4,Andrew Belle,Sky's Still Blue,6nXIYClvJAfi6ujLiKqEq8,54,2012,acoustic,0.430,0.791,6,-5.419,0,0.0302,0.0726,0.019300,0.1100,0.217,171.864,244320,4

In [3]:
# Dit is de een deel van de dataset van spotify van 1000 random playlists
# https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files
with open('data/mpd.slice.0-999.json') as f:
    data = json.load(f)

df_spot = pd.DataFrame(data['playlists'])
df_spot.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN

In [4]:
# Dit is het tweede deel van de dataset van spotify van 1000 random playlists
# https://www.aicrowd.com/challenges/spotify-million-playlist-dataset-challenge/dataset_files
with open('data/mpd.slice.1000-1999.json') as f:
    data = json.load(f)

df_spot2 = pd.DataFrame(data['playlists'])
df_spot2.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,disney,false,1000,1457827200,189,16,1,"[{'pos': 0, 'artist_name': 'Original Broadway ...",4,31428282,65,NaN
1,Indie Electro,false,1001,1417824000,165,18,2,"[{'pos': 0, 'artist_name': 'The Octopus Projec...",2,38241566,8,NaN
2,jack & jack,false,1002,1465430400,17,14,1,"[{'pos': 0, 'artist_name': 'Jack & Jack', 'tra...",3,3549358,3,NaN
3,vibes,false,1003,1498435200,225,195,2,"[{'pos': 0, 'artist_name': 'LANY', 'track_uri'...",91,51242585,157,NaN
4,Indie,false,1004,1498608000,165,118,1,"[{'pos': 0, 'artist_name': 'Youth Lagoon', 'tr...",74,42601098,92,NaN

In [5]:
# Hier wordt er per artiest geteld hoe vaak hun naam voorkomt in de kolom tracks.
# Hierdoor hou je bij hoe vaak een bepaalde
# artiest voorkomt in 1000 playlists.
df_tracks1 = df_spot.explode('tracks')
df_tracks1['artist_name'] = df_tracks1['tracks'].apply(lambda x: x['artist_name'])

artist_counts1 = df_tracks1['artist_name'].value_counts()
artist_counts1.head()

artist_name
Drake             939
Kanye West        415
Kendrick Lamar    385
Rihanna           350
Eminem            332
Name: count, dtype: int64

In [6]:
# Hier wordt er per artiest geteld hoe vaak hun naam voorkomt in de kolom tracks.
# Hierdoor hou je bij hoe vaak een bepaalde
# artiest voorkomt in 1000 playlists. Maar dan hier bij het tweede deel.
df_tracks2 = df_spot2.explode('tracks')
df_tracks2['artist_name'] = df_tracks2['tracks'].apply(lambda x: x['artist_name'])

artist_counts2 = df_tracks2['artist_name'].value_counts()
artist_counts2.head()

artist_name
Drake             990
The Beatles       351
The Weeknd        348
Kendrick Lamar    337
Kanye West        314
Name: count, dtype: int64

In [7]:
# Hier worden de twee dataframes van de 1000 playlists gecombineerd
# om totaal te berekenen hoe vaak een artiest voorkomt in 2000
# playlists.
combined = pd.concat([df_spot, df_spot2], ignore_index=True)
combined.head()

,name,collaborative,pid,modified_at,num_tracks,num_albums,num_followers,tracks,num_edits,duration_ms,num_artists,description
0,Throwbacks,false,0,1493424000,52,47,1,"[{'pos': 0, 'artist_name': 'Missy Elliott', 't...",6,11532414,37,NaN
1,Awesome Playlist,false,1,1506556800,39,23,1,"[{'pos': 0, 'artist_name': 'Survivor', 'track_...",5,11656470,21,NaN
2,korean,false,2,1505692800,64,51,1,"[{'pos': 0, 'artist_name': 'Hoody', 'track_uri...",18,14039958,31,NaN
3,mat,false,3,1501027200,126,107,1,"[{'pos': 0, 'artist_name': 'Camille Saint-Saën...",4,28926058,86,NaN
4,90s,false,4,1401667200,17,16,2,"[{'pos': 0, 'artist_name': 'The Smashing Pumpk...",7,4335282,16,NaN

In [8]:
# Dit zijn alle counts uit 2 files bij elkaar opgeteld. Dus hoe vaak een bepaalde artiest in 2000 playlists voorkomt.
df_tracks = combined.explode('tracks')

df_tracks['artist_name'] = df_tracks['tracks'].apply(lambda x: x['artist_name'])

artist_counts = df_tracks['artist_name'].value_counts()

artist_counts.head()

artist_name
Drake             1929
Kanye West         729
Kendrick Lamar     722
The Weeknd         644
Rihanna            613
Name: count, dtype: int64

In [9]:
# Dit is de montly listeners dataset
# https://www.kaggle.com/datasets/meeratif/spotify-top-artists-by-monthly-listeners/data
df_listeners = pd.read_csv('./data/listeners.csv')
df_listeners.head()

         Artist    Listeners Daily Trend  Peak  PkListeners
0    The Weeknd  107,592,328    -138,880     1  113,034,886
1  Taylor Swift  101,003,302         889     2  101,003,302
2    Ed Sheeran   76,475,126     -68,137     2   87,934,910
3      Dua Lipa   76,421,916     -71,356     4   77,778,397
4     Bad Bunny   76,162,057    -199,052     3   83,950,570